apiVersion: v1
entries:
  prometheus-vpc-flow-metrics:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-16T20:32:22.342871605Z"
    description: Signicat Prometheus VPC Flow Metrics
    digest: e4c7508254561fda0a7ff988a570274c929307475178b4890f14da845947d9ad
    name: prometheus-vpc-flow-metrics
    type: application
    urls:
    - prometheus-vpc-flow-metrics-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-16T20:32:22.342394928Z"
